// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY4_1b3YblNkWAcBwqfeTaJszzWomK4-Y',
    appId: '1:1017678726878:web:528731279b58ee5521e44f',
    messagingSenderId: '1017678726878',
    projectId: 'signwayai',
    authDomain: 'signwayai.firebaseapp.com',
    storageBucket: 'signwayai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl3iPPz63M9AKdlR6KzmG51iES3LMcD3c',
    appId: '1:1017678726878:android:d615547e758cca1321e44f',
    messagingSenderId: '1017678726878',
    projectId: 'signwayai',
    storageBucket: 'signwayai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnyHlEhWpVFpgsRO5AdZf9t3-BEkbXU-M',
    appId: '1:1017678726878:ios:4e328ed70537fc1321e44f',
    messagingSenderId: '1017678726878',
    projectId: 'signwayai',
    storageBucket: 'signwayai.appspot.com',
    iosBundleId: 'com.example.signway3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnyHlEhWpVFpgsRO5AdZf9t3-BEkbXU-M',
    appId: '1:1017678726878:ios:561a55e80969a11321e44f',
    messagingSenderId: '1017678726878',
    projectId: 'signwayai',
    storageBucket: 'signwayai.appspot.com',
    iosBundleId: 'com.example.signway3.RunnerTests',
  );
}
